language: go

go:
  - 1.x

os:
  - linux

env:
  - CODECOV_TOKEN="b6646c9b-e648-418a-b805-849cb5692b54"
before_install:
  - cd dwolla
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
